###POST
POST https://localhost:5001/v1/type-key
Content-Type: application/json

{
    "QuantityKey" : 2,
    "Championship": {
    "id": 1
  }
}

###LIST
GET https://localhost:5001/v1/type-key

###PUT
PUT https://localhost:5001/v1/type-key
Content-Type: application/json

{
    "id": 1,
    "QuantityKey" : 1
}